### ISSUE TITLE
Adding cost to the Resources

### ISSUE THREAD

**Issue by manwaarahmed** [Cape-Code/vsts-time-and-effort#11]
I would be great full if any one can answer my query, since I could not find any category on VSTS to address this issue there.

1-  By selecting the Time and Effort option from the gear, I created the following Roles and assign per cost of each.
a- Business Analyst
b- Developer &
c- Project Manager 

![time and effort](https://user-images.githubusercontent.com/38782602/39356039-75c8abaa-4a28-11e8-81b0-eaa0807017ce.png)
2-  Now when I clicked on Time option from the work tab, the following screen appeared:

![time](https://user-images.githubusercontent.com/38782602/39356158-b7c8f708-4a28-11e8-9a34-5b0f7d1a4fd9.png)

Here I can only view the time spent by the developer with the associated cost. 

I just want to confirm where can I assign the roles (Developer,  Business Analyst e.t.c) to an individual?, does this option work when iterations are enabled in the system because currently we have disabled the iterations for the time being. Please advice. 

Waiting for your reply.

**Comment by cc-fabianvo** [comment]
Roles can be used by any user while creating estimates or tracking time, but there is no option to assign roles to an individual to filter their list of available roles.

Roles are not used for any authorization, but only to indicate which cost should be associated with each booking. Costs per role can be customized per budget.

I hope this helps.

**Comment by cc-fabianvo** [comment]
I am sorry, I do not understand your question. Are you asking in regard to this extension or VSTS in general?

The settings (roles, customers, and budgets) are just for this extension and not integrated with the rest of VSTS at all.
